name: Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      uses: ilammy/msvc-dev-cmd@v1.5.0
      with:
        arch: x64
        
    - name: Compile
      run: |
        mkdir bin
        cd bin
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ../
        ninja
        mkdir output
        mkdir output/rainbomizer
        cp V.Rainbomizer.asi output/V.Rainbomizer.asi
        cp -r ../data output/rainbomizer/data/
        rm output/rainbomizer/data/update.sh
        rm output/rainbomizer/data/README.md
        cp ../config.toml output/rainbomizer/
        
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: "V.Rainbomizer"
        path: bin/output
        
